"""Turn the LLM pipeline into a teacher, so a small model can be the student.

WHY THIS EXISTS
---------------
In the CSAI subcategory the first question is "which part is machine learning?"
Calling a hosted model through an API is not an answer. Training one is.

This module converts the existing extraction pipeline's output into training data
for a small Thai encoder. The pipeline stops being the contribution and becomes
the *teacher*; the contribution becomes the student model and the measured
question of whether it can replace the teacher.

    THE RESEARCH QUESTION
    Can a small, locally-runnable Thai model, trained on annotations generated by
    a large language model, match that model at extracting geolocated occurrence
    records -- at a fraction of the cost and with no API dependency?

That is genuine ML with a clean baseline (the teacher), a clean metric (accuracy
against a gold set the teacher never saw), and an informative failure mode: the
student is expected to match on easy mentions and lose on ambiguous ones. The
size of that gap is the result.

TWO LABEL QUALITIES, NEVER MIXED
--------------------------------
  SILVER  produced by the teacher, cheap, plentiful, and imperfect. Training only.
  GOLD    hand-labelled by you, expensive, scarce, correct. Evaluation only.

Never evaluate on silver. Never train on gold. A student evaluated on its
teacher's output measures agreement with the teacher, not correctness -- and if
the teacher is wrong in a systematic way, the student inherits the error and the
evaluation cannot see it.
"""

from __future__ import annotations

import json
import random
from dataclasses import asdict, dataclass
from pathlib import Path

from .extract import SourceDocument
from .schema import DocumentExtraction


@dataclass
class TokenTaggedExample:
    """One document as a token-classification example (place-mention NER).

    BIO tagging over characters rather than words, because Thai has no
    inter-word spaces and any word segmenter introduces its own errors --
    errors that would then be scored as the model's. Character-level tagging
    sidesteps that, and Thai encoders handle it.
    """

    text: str
    labels: list[str]           # per character: O / B-PLACE / I-PLACE
    source_id: str
    label_quality: str = "silver"


@dataclass
class LinkingExample:
    """One mention with its gazetteer candidates, for learning-to-rank.

    This is the half where the interesting ML lives. Detecting that ต.บางแก้ว is
    a place is comparatively easy; deciding *which* บางแก้ว requires combining
    string similarity, hierarchical consistency with other mentions in the
    document, and a prior over which administrative units appear at all.

    A learned ranker over those features versus the hand-written rules in
    geocode.py is a direct, publishable comparison -- and "the rules won at this
    data size" is a legitimate outcome worth reporting.
    """

    mention: str
    context_window: str
    candidate_codes: list[str]
    gold_index: int | None       # None = correct answer is "cannot resolve"
    features: list[list[float]]
    source_id: str
    label_quality: str = "silver"


def to_char_bio(text: str, mentions: list[str]) -> list[str]:
    """Character-level BIO tags for the given verbatim mention strings.

    Only tags exact substring occurrences. A mention the extractor reported but
    that does not appear verbatim is skipped rather than fuzzily aligned --
    silently mis-aligned training labels are worse than fewer labels, and the
    grounding check upstream should already have removed those records.
    """
    labels = ["O"] * len(text)
    for mention in sorted(set(mentions), key=len, reverse=True):
        if not mention:
            continue
        start = text.find(mention)
        while start != -1:
            if all(labels[i] == "O" for i in range(start, start + len(mention))):
                labels[start] = "B-PLACE"
                for i in range(start + 1, start + len(mention)):
                    labels[i] = "I-PLACE"
            start = text.find(mention, start + 1)
    return labels


def build_ner_dataset(
    documents: dict[str, SourceDocument],
    extractions: dict[str, DocumentExtraction],
) -> list[TokenTaggedExample]:
    """Teacher output -> character-tagged NER training data."""
    examples = []
    for source_id, extraction in extractions.items():
        doc = documents.get(source_id)
        if doc is None:
            continue
        mentions = [m.raw_place_text for m in extraction.mentions]
        examples.append(
            TokenTaggedExample(
                text=doc.text,
                labels=to_char_bio(doc.text, mentions),
                source_id=source_id,
            )
        )
    return examples


def candidate_features(mention: str, context: str, candidate, gazetteer) -> list[float]:
    """Features for one (mention, candidate) pair.

    Deliberately few and interpretable. With a few thousand training examples a
    large feature set overfits, and an explainable ranker is far easier to defend
    at a poster than an opaque one. Extend only when a measured error analysis
    says a feature is missing.
    """
    from rapidfuzz import fuzz

    from .geocode import normalise

    key = normalise(mention)
    name = normalise(candidate.own_name)
    ctx = normalise(context) if context else ""

    return [
        1.0 if key == name else 0.0,                         # exact match
        fuzz.ratio(key, name) / 100.0,                       # string similarity
        1.0 if ctx and normalise(candidate.adm1_name) in ctx else 0.0,   # province in context
        1.0 if ctx and normalise(candidate.adm2_name or "") in ctx else 0.0,  # district in context
        {"tambon": 0.0, "amphoe": 0.5, "changwat": 1.0}.get(candidate.level, 0.0),
        len(gazetteer._by_name.get(name, [])) / 10.0,        # ambiguity of this name
    ]


def build_linking_dataset(
    extractions: dict[str, DocumentExtraction],
    gazetteer,
    max_candidates: int = 8,
) -> list[LinkingExample]:
    """Teacher output -> learning-to-rank training data for disambiguation.

    The gold index comes from the rule-based resolver, which makes this
    *self-distillation of the rules*. State that plainly: a ranker trained this
    way can at best reproduce the rules, so the honest framing is "can a learned
    model recover hand-written domain rules from data" -- interesting, and a
    different claim from "the learned model is better".

    To make the stronger claim, re-label these instances by hand. Then the
    comparison is learned-vs-rules against ground truth, and either can win.
    """
    from .geocode import normalise

    examples = []
    for source_id, extraction in extractions.items():
        for m in extraction.mentions:
            key = normalise(m.raw_place_text)
            candidates = gazetteer._by_name.get(key, [])[:max_candidates]
            if not candidates:
                continue

            resolved = gazetteer.resolve(m.raw_place_text, m.place_context)
            gold_code = None
            if resolved.unit is not None:
                gold_code = (
                    resolved.unit.adm3_code
                    or resolved.unit.adm2_code
                    or resolved.unit.adm1_code
                )

            codes = [c.adm3_code or c.adm2_code or c.adm1_code for c in candidates]
            gold_index = codes.index(gold_code) if gold_code in codes else None

            examples.append(
                LinkingExample(
                    mention=m.raw_place_text,
                    context_window=m.place_context or "",
                    candidate_codes=[str(c) for c in codes],
                    gold_index=gold_index,
                    features=[
                        candidate_features(m.raw_place_text, m.place_context or "", c, gazetteer)
                        for c in candidates
                    ],
                    source_id=source_id,
                )
            )
    return examples


def write_jsonl(examples: list, path: Path) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        for example in examples:
            handle.write(json.dumps(asdict(example), ensure_ascii=False) + "\n")
    return len(examples)


def learning_curve_splits(
    examples: list, sizes: tuple[int, ...] = (250, 500, 1000, 2000, 4000), seed: int = 0
) -> dict[int, list]:
    """Nested training subsets for a label-efficiency curve.

    Train the student at each size and plot accuracy against training-set size.
    This is the most informative single figure a CSAI entry can show: it answers
    how much teacher annotation is actually needed, whether performance has
    plateaued, and therefore whether spending more on the teacher would help.

    Subsets are nested, so the curve reflects added data rather than a different
    random draw at each point.
    """
    pool = list(examples)
    random.Random(seed).shuffle(pool)
    return {size: pool[:size] for size in sizes if size <= len(pool)}
